---
services:
  
  devopsdb:
    image: apsanadevops/myfirstdockerrepo:dbimg
    ports:
      - "2222:3306"
    deploy:
      replicas: 3
  
  app:
    image: apsanadevops/myfirstdockerrepo:appimg
    ports:
      - "1111:8080"
    deploy:
      replicas: 3
     
   
...
