---
services:
  
  db:
    image: dbimg
    ports:
      - "2222:3306"
    deploy:
      replicas: 3
  
  app:
    image: appimg
    ports:
      - "1111:8080"
    deploy:
      replicas: 3
     
   
...
