---
version : "3"
services :
  dbimg :
    container_name : devopsdb
    build : ./Docker-db
    ports :
      - "2222:3306"

  appimg :
    container_name : appcont
    build : ./Docker-app
    ports :
      - "3333:8080"

...
